services:
  - type: web
    name: seekwell-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ALLOWED_ORIGINS
        value: '["https://seekwell-frontend.vercel.app", "https://seekwell.vercel.app", "http://localhost:3000"]'
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health

databases:
  - name: seekwell-postgres
    databaseName: seekwell
    user: seekwell
    region: oregon
    plan: starter
